./tree/tree --input ./T0/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T0/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T0/LIVER-BGI.list.txt.train --coverage 0.6 > ./T0/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T0/LUNG-BGI.list.txt.train --coverage 0.6 > ./T0/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T1/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T1/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T1/LIVER-BGI.list.txt.train --coverage 0.6 > ./T1/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T1/LUNG-BGI.list.txt.train --coverage 0.6 > ./T1/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T2/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T2/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T2/LIVER-BGI.list.txt.train --coverage 0.6 > ./T2/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T2/LUNG-BGI.list.txt.train --coverage 0.6 > ./T2/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T3/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T3/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T3/LIVER-BGI.list.txt.train --coverage 0.6 > ./T3/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T3/LUNG-BGI.list.txt.train --coverage 0.6 > ./T3/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T4/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T4/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T4/LIVER-BGI.list.txt.train --coverage 0.6 > ./T4/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T4/LUNG-BGI.list.txt.train --coverage 0.6 > ./T4/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T5/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T5/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T5/LIVER-BGI.list.txt.train --coverage 0.6 > ./T5/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T5/LUNG-BGI.list.txt.train --coverage 0.6 > ./T5/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T6/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T6/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T6/LIVER-BGI.list.txt.train --coverage 0.6 > ./T6/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T6/LUNG-BGI.list.txt.train --coverage 0.6 > ./T6/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T7/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T7/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T7/LIVER-BGI.list.txt.train --coverage 0.6 > ./T7/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T7/LUNG-BGI.list.txt.train --coverage 0.6 > ./T7/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T8/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T8/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T8/LIVER-BGI.list.txt.train --coverage 0.6 > ./T8/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T8/LUNG-BGI.list.txt.train --coverage 0.6 > ./T8/LUNG-BGI.list.txt.train.half
./tree/tree --input ./T9/HEALTH-BGI.list.txt.train --coverage 0.6 > ./T9/HEALTH-BGI.list.txt.train.half
./tree/tree --input ./T9/LIVER-BGI.list.txt.train --coverage 0.6 > ./T9/LIVER-BGI.list.txt.train.half
./tree/tree --input ./T9/LUNG-BGI.list.txt.train --coverage 0.6 > ./T9/LUNG-BGI.list.txt.train.half
